# Problema 2 
## Sebastian Ramirez Escobar 
## Sebastian Carvalho Salazar
## Johan Stiven Paez Bermudez

### Descripción del problema:
1. Descargue un conjunto de datos y elija 4 variables numéricas según su interés. Calcule el vector de medias, la matriz de covarianzas y su inversa.
2. Llame Z a la matriz de datos obtenida al restar la media de cada observación. ¿Cuál es la relación entre Z TZ y la matriz de covarianza?
3. Calcule la distancia de Mahalanobis de cada observación respecto al vector de medias. Realice una gráfica de dispersión de variables dos a dos coloreando cada observación de acuerdo con la distancia calculada.
4. Identifique la bola de radio 1 con centro en el vector de medias respecto a la distancia de Mahalanobis en la gráfica del punto anterior.


# Vector de medias, matriz de covarianzas y su inversa.

In [4]:
import pandas as pd
import numpy as np

# Leer el conjunto de datos
path = './content/pima-indians-diabetes.csv'
df = pd.read_csv(path, sep=",",
                  names=[
                      "pregnancies",
                      "glucose",
                      "blood_pressure",
                      "skin_thickness",
                      "insulin",
                      "bmi",
                      "diabetes_pedigree_function",
                      "age",
                      "outcome",
                  ])

# Seleccionar 4 variables numéricas de interés (por ejemplo: glucose, bmi, blood_pressure, age)
selected_columns = ["glucose", "bmi", "blood_pressure", "age"]
selected_data = df[selected_columns]

# Calcular el vector de medias
mean_vector = selected_data.mean()

# Calcular la matriz de covarianzas
covariance_matrix = selected_data.cov()

# Calcular la inversa de la matriz de covarianzas
covariance_inverse = np.linalg.inv(covariance_matrix)

# Calcular Z, la matriz de datos centrados
Z = selected_data - mean_vector

# Calcular Z_Transpuesta * Z
Z_transpose_Z = np.dot(Z.T, Z)

# Imprimir resultados
print("Vector de Medias:")
print(mean_vector)
print("\nMatriz de Covarianzas:")
print(covariance_matrix)
print("\nInversa de la Matriz de Covarianzas:")
print(covariance_inverse)
print("\nZ_Transpuesta * Z:")
print(Z_transpose_Z)
print("\n(Z_Transpuesta * Z) / (n-1):")
print(Z_transpose_Z/(len(df)-1))

Vector de Medias:
glucose           120.894531
bmi                31.992578
blood_pressure     69.105469
age                33.240885
dtype: float64

Matriz de Covarianzas:
                    glucose        bmi  blood_pressure         age
glucose         1022.248314  55.726987       94.430956   99.082805
bmi               55.726987  62.159984       43.004695    3.360330
blood_pressure    94.430956  43.004695      374.647271   54.523453
age               99.082805   3.360330       54.523453  138.303046

Inversa de la Matriz de Covarianzas:
[[ 1.10584097e-03 -9.05130355e-04 -6.65546392e-05 -7.44014710e-04]
 [-9.05130355e-04  1.82358560e-02 -2.01033043e-03  9.97913803e-04]
 [-6.65546392e-05 -2.01033043e-03  3.07933790e-03 -1.11744712e-03]
 [-7.44014710e-04  9.97913803e-04 -1.11744712e-03  8.17981132e-03]]

Z_Transpuesta * Z:
[[784064.45703125  42742.59882813  72428.54296875  75996.51171875]
 [ 42742.59882813  47676.70769531  32984.60117187   2577.37304688]
 [ 72428.54296875  32984.601171